package com.m2.entity;


import java.util.List;
/**
 * FuncTree generated by MyEclipse - Hibernate Tools
 */

public class FuncTree  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer parentId;
     private Integer layer;
     private String name;
     private Integer sort;
     private String description;
     
     
     
     private List childFunctions;


    // Constructors

    /** default constructor */
    public FuncTree() {
    }

    
    /** full constructor */
    public FuncTree(Integer parentId, Integer layer, String name, Integer sort, String description) {
        this.parentId = parentId;
        this.layer = layer;
        this.name = name;
        this.sort = sort;
        this.description = description;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Integer getLayer() {
        return this.layer;
    }
    
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getSort() {
        return this.sort;
    }
    
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


	public List getChildFunctions() {
		return childFunctions;
	}


	public void setChildFunctions(List childFunctions) {
		this.childFunctions = childFunctions;
	}
    
    
    
   








}