package com.m2.entity;



/**
 * Function generated by MyEclipse - Hibernate Tools
 */

public class Function  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String resource;
     private String params;
     private String description;
     private FuncTree funcTree;


    // Constructors

    /** default constructor */
    public Function() {
    }

    
    /** full constructor */
    public Function(String name, String resource, String params, String description, FuncTree funcTree) {
        this.name = name;
        this.resource = resource;
        this.params = params;
        this.description = description;
        this.funcTree = funcTree;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getResource() {
        return this.resource;
    }
    
    public void setResource(String resource) {
        this.resource = resource;
    }

    public String getParams() {
        return this.params;
    }
    
    public void setParams(String params) {
        this.params = params;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public FuncTree getFuncTree() {
        return this.funcTree;
    }
    
    public void setFuncTree(FuncTree funcTree) {
        this.funcTree = funcTree;
    }
   








}