package com.m2.entity;

import java.util.HashSet;
import java.util.Set;


/**
 * Group generated by MyEclipse - Hibernate Tools
 */

public class Group  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String type;
     private String description;
     private Set roles = new HashSet(0);


    // Constructors

    /** default constructor */
    public Group() {
    }

    
    /** full constructor */
    public Group(String name, String type, String description, Set roles) {
        this.name = name;
        this.type = type;
        this.description = description;
        this.roles = roles;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }
   








}