package com.m2.entity;



/**
 * Org generated by MyEclipse - Hibernate Tools
 */

public class Org  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private Integer parentId;
     private String description;


    // Constructors

    /** default constructor */
    public Org() {
    }

    
    /** full constructor */
    public Org(String name, Integer parentId, String description) {
        this.name = name;
        this.parentId = parentId;
        this.description = description;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}