package com.m2.entity;

import com.m2.usertype.hibernate.IntegerSplitList;
import java.util.*;


/**
 * Role generated by MyEclipse - Hibernate Tools
 */

public class Role  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String type;
     private String description;
     private List functions =new ArrayList();


    // Constructors

    /** default constructor */
    public Role() {
    }

    
    /** full constructor */
    public Role(String name, String type, String description, List functions) {
        this.name = name;
        this.type = type;
        this.description = description;
        this.functions = functions;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public List getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(List functions) {
        this.functions = functions;
    }
   








}