package com.m2.entity;

import java.util.HashSet;
import java.util.Set;


/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String realName;
     private String loginName;
     private String password;
     private String rePassword;
     private String description;
     private int isEnabled;
     private Group group;
     private Org org;
     private Set roles = new HashSet(0);


    // Constructors

    /** default constructor */
    public User() {
    }

    
    /** full constructor */
    public User(String realName, String loginName, String password, String rePassword, String description, int isEnabled, Group group, Org org, Set roles) {
        this.realName = realName;
        this.loginName = loginName;
        this.password = password;
        this.rePassword = rePassword;
        this.description = description;
        this.isEnabled = isEnabled;
        this.group = group;
        this.org = org;
        this.roles = roles;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getRePassword() {
        return this.rePassword;
    }
    
    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public int getIsEnabled() {
        return this.isEnabled;
    }
    
    public void setIsEnabled(int isEnabled) {
        this.isEnabled = isEnabled;
    }

    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }

    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }
   








}