package com.source.bean;

import java.util.Date;

/**
 * AnythingType generated by MyEclipse - Hibernate Tools
 */

public class AnythingType implements java.io.Serializable
{

	private static final long serialVersionUID=-7763613924989231739L;

	private Integer classId;

	private String className;

	private String classMark;

	private Date createDate;

	// Constructors

	/** default constructor */
	public AnythingType()
	{}

	/** full constructor */
	public AnythingType(String className,String classMark,Date createDate)
	{
		this.className=className;
		this.classMark=classMark;
		this.createDate=createDate;
	}

	// Property accessors

	public Integer getClassId()
	{
		return this.classId;
	}

	public void setClassId(Integer classId)
	{
		this.classId=classId;
	}

	public String getClassName()
	{
		return this.className;
	}

	public void setClassName(String className)
	{
		this.className=className;
	}

	public String getClassMark()
	{
		return this.classMark;
	}

	public void setClassMark(String classMark)
	{
		this.classMark=classMark;
	}

	public Date getCreateDate()
	{
		return createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate=createDate;
	}

}
